'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {adminStatus}=require('../scripts/build-admin-status.cjs');
test('admin reports actual results and never treats local execution as automated success',()=>{
 const registry=require('../sources/registry.json'),snapshot=require('../dist/source-snapshot.json'),report=require('../dist/collector-status.json');
 const status=adminStatus(registry,report,snapshot,{configured:true,verifiedRun:false});assert.equal(status.sources.length,registry.sources.length);assert.equal(registry.sources.filter(s=>s.original45).length,45);assert.equal(status.sources.filter(s=>s.autoRefreshVerified).length,0);assert.equal(status.sources.filter(s=>s.fullCatalogCoverage).length,0);
 for(const s of status.sources){assert.equal(s.discovery.coverageComplete,false);assert.equal(s.discovery.newProductDiscovery,['cafe24_category_links','makeshop_category_links','godo_category_links','imweb_category_links','wpet_category_links'].includes(s.discovery.adapter));assert.equal(s.snapshotProductCount,snapshot.items.filter(p=>p.seller_domain===s.domain).length);}
});
test('admin contains only read-only navigation and escapes retailer text',()=>{
 const js=fs.readFileSync('dist/admin/app.js','utf8'),html=fs.readFileSync('dist/admin/index.html','utf8');assert.match(js,/escapeText/);assert.doesNotMatch(js,/localStorage|method\s*:\s*['"](?:POST|PUT|DELETE)/);assert.match(html,/github\.com\/joonhyoung-kim\/aqua-price\/edit\/preview\/sources\/registry\.json/);
});
test('publisher adds a new product without photo and preserves failed-source lastgood',()=>{
 const {applyUpdates}=require('../scripts/collector/publish.cjs'),snapshot=require('../dist/source-snapshot.json');const product=structuredClone(snapshot.items[0]);product.id='synthetic-test-only';product.collector_key=product.id;product.photo=null;
 const output=applyUpdates(snapshot,{ok:{status:'success',cacheOnly:false,products:[product],updatedKeys:[product.id]},failed:{status:'failed',products:[],updatedKeys:[]}});assert.equal(output.snapshot.items.length,snapshot.items.length+1);assert.equal(output.catalog.products.at(-1).photo.url,null);
});
test('admin discovery column matches header and escapes cursor/error values',async()=>{const vm=require('node:vm'),nodes={};for(const id of ['query','statusFilter','rows','summary','automation','updated','scope'])nodes[id]={value:id==='statusFilter'?'all':'',innerHTML:'',textContent:'',addEventListener(){}};const source={id:'x',name:'safe',domain:'example.invalid',officialUrl:'https://example.invalid',enabled:true,collectorStatus:'success',technicalReadiness:'ready',snapshotProductCount:1,collectorProductCount:1,blockers:[],discovery:{mappedSeedCount:1,status:'budget_limited',cursorCategories:[{entryUrl:'<script>bad</script>',nextUrl:'<img src=x>'}],errors:['<img onerror=x>']}};vm.runInNewContext(fs.readFileSync('dist/admin/app.js','utf8'),{document:{querySelector:s=>nodes[s.slice(1)]},fetch:async()=>({ok:true,json:async()=>({schemaVersion:1,sources:[source],automation:{configured:true,verifiedRun:false},additionalSnapshotDomains:[],discoveryScope:{mappedSources:32,observedSeeds:139,adapterEnabledSources:26},generatedAt:'test'})})});await new Promise(resolve=>setImmediate(resolve));assert.equal((nodes.rows.innerHTML.match(/<td\b/g)||[]).length,7);assert.equal((fs.readFileSync('dist/admin/index.html','utf8').match(/<th>/g)||[]).length,7);assert.ok(!nodes.rows.innerHTML.includes('<script>'));assert.match(nodes.rows.innerHTML,/&lt;script&gt;/);assert.match(nodes.scope.textContent,/32곳/);assert.match(nodes.scope.textContent,/139개/);});
