'use strict';const {test}=require('node:test'),assert=require('node:assert/strict');const {categoryLinks,mergeTree,treeProgress}=require('../scripts/collector/category-tree.cjs');
const source={id:'test',officialURL:'https://example.invalid/',enabled:true},seed={adapter:'cafe24_category_links',categories:[{url:'https://example.invalid/category/live/1/',label:'생물',mixedCategories:true,excluded:false}]};
test('Cafe24 child block inherits observed parent while unrelated navigation remains unresolved',()=>{const html='<ul><li><a href="/category/unrelated/9/">입문용</a></li></ul><ul class="menuCategory"><li><a href="/category/normal/2/">노멀</a></li><li><a href="/category/feed/3/">사료</a></li></ul>',nodes=categoryLinks(html,seed.categories[0].url,source,seed.adapter,['구피']);assert.equal(nodes.find(n=>n.key==='example.invalid:2').subtype,'fish');assert.deepEqual(nodes.find(n=>n.key==='example.invalid:2').ancestorLabels,['구피']);assert.equal(nodes.find(n=>n.key==='example.invalid:9').scope,'review');assert.equal(nodes.find(n=>n.key==='example.invalid:3').scope,'excluded');});
test('recommended packaging cannot count as a fish or a normal category-list product',()=>{const {classifyProduct}=require('../scripts/collector/classification.cjs'),{parseCategoryPage}=require('../scripts/collector/discovery.cjs');assert.equal(classifyProduct('',{title:'생물 포장비 [핫팩+스티로폼]'},{type:'live',subtype:'fish',url:'https://example.invalid/product/x/4/'},seed).type,'gear');const html='<div class="xans-product-listrecommend"><ul class="prdList"><a href="/product/pack/4/">포장비</a></ul></div><ul class="prdList"><a href="/product/fish/5/">베타</a></ul><div class="xans-product-normalpaging"></div>';const parsed=parseCategoryPage(html,seed.categories[0].url,source.officialURL);assert.deepEqual(parsed.products,['https://example.invalid/product/fish/5/']);});
test('named source checkpoint survives source-priority reorder and reaches unvisited sellers',()=>{const {sourceCursor}=require('../scripts/collector/queue-policy.cjs'),prior={runCursors:{reconcile:1},runNextSourceIds:{reconcile:'b'}};assert.equal(sourceCursor([{id:'b'},{id:'a'},{id:'c'}],prior,'reconcile'),0);assert.equal(sourceCursor([{id:'a'},{id:'c'},{id:'b'}],prior,'reconcile'),2);});
test('tree follows observed nested category hrefs and excludes fish-named feed siblings without guessed paths',()=>{
 const html='<ul><li><a href="/category/live/1/">생물</a><ul><li><a href="/category/fish/2/">시클리드</a><ul><li><a href="/category/species/3/">피콕</a></li></ul></li><li><a href="/category/shrimp/4/">새우/가재</a></li><li><a href="/category/reptile/5/">파충류</a></li></ul></li><li><a href="/category/feed/6/">사료</a><ul><li><a href="/category/betta/7/">베타</a></li></ul></li><li><a href="https://evil.invalid/category/fish/8/">코리</a></li></ul>';
 const nodes=categoryLinks(html,seed.categories[0].url,source,seed.adapter);assert.equal(nodes.length,7);assert.equal(nodes.find(n=>n.key==='example.invalid:3').subtype,'fish');assert.equal(nodes.find(n=>n.key==='example.invalid:7').scope,'excluded');assert.equal(nodes.find(n=>n.key==='example.invalid:4').subtype,'shrimp');assert.equal(nodes.find(n=>n.key==='example.invalid:5').scope,'excluded');assert.ok(!nodes.some(n=>n.url.includes('evil')));
 const state={cache:{[seed.categories[0].url]:{text:html,fetchedAt:'2026-10-08T18:00:00Z'}}},merged=mergeTree(source,seed,state);assert.ok(merged.seed.categories.some(c=>c.url.endsWith('/3/')));assert.ok(!merged.seed.categories.some(c=>c.url.endsWith('/7/')));assert.equal(merged.tree.fullMenuCoverage,'unknown');
});
test('cold checkpoint persists tree, detail queue and actual page tails and cannot label a budget-limited source complete',()=>{
 const {progress,restoreCheckpoint}=require('../scripts/collector/queue-policy.cjs'),state={products:[],detailQueueCursor:6,categoryTree:{nodes:[{key:'example.invalid:2',url:'https://example.invalid/category/fish/2/',scope:'live'},{key:'example.invalid:3',url:'https://example.invalid/category/fish/3/',scope:'live'}],excludedCategoryCount:0,reviewCategoryCount:0},dailyDiscovery:{cursor:{schemaVersion:1,categories:{'example.invalid:2':{nextUrl:'https://example.invalid/category/fish/2/?page=2',visitedPageUrls:['https://example.invalid/category/fish/2/']}}}},discoveryPending:[{url:'https://example.invalid/product/x/99/'}]};
 const p=progress(state),restored=restoreCheckpoint({}, {items:[]},source,{discoveryProgress:p});assert.deepEqual(restored.categoryTree,state.categoryTree);assert.equal(restored.detailQueueCursor,6);const t=treeProgress(restored);assert.equal(t.pendingCategoryCount,2);assert.equal(t.pagesVisited,1);assert.equal(t.pendingProductCount,1);assert.equal(t.terminalCoverage,'incomplete');assert.equal(t.fullRetailerCoverage,false);
});
