'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),{spawnSync}=require('child_process');
test('scheduled live mode discovers a seller with no registered product URLs and publishes a recoverable source checkpoint',()=>{
 const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'aqua-tree-cli-')),repo=path.join(__dirname,'..'),save=(p,v)=>fs.writeFileSync(path.join(cwd,p),JSON.stringify(v));
 try{fs.cpSync(path.join(repo,'scripts'),path.join(cwd,'scripts'),{recursive:true});for(const d of ['dist','sources'])fs.mkdirSync(path.join(cwd,d));fs.copyFileSync(path.join(repo,'dist/data-model.js'),path.join(cwd,'dist/data-model.js'));
 const snapshot=require('../dist/source-snapshot.json');save('dist/source-snapshot.json',{...snapshot,items:snapshot.items.slice(0,1)});save('dist/collector-status.json',{sources:[]});const host='https://example.invalid',category=host+'/category/betta/1/',product=host+'/product/betta/99/';
 save('sources/registry.json',{sources:[{id:'test',name:'Fixture',sourceDomain:'example.invalid',officialURL:host,enabled:true,products:[],maxRequests:5,delayMs:0,cacheTtlMs:10800000,timeoutMs:1000,maxBytes:10000}]});save('sources/discovery-seeds.json',{sources:[{id:'test',adapter:'cafe24_category_links',maxPages:1,maxProducts:3,maxProductVerifications:2,categories:[{url:category,label:'베타',type:'live',subtype:'fish',reviewBasis:'Fixture'}]}]});
 const html='<h1>검증 베타</h1><p>1,000원</p><script type="application/ld+json">'+JSON.stringify({'@type':'Product',name:'검증 베타',sku:'99',url:product,offers:{'@type':'Offer',price:1000,priceCurrency:'KRW'}})+'</script>';
 save('transport.json',{[host+'/robots.txt']:'User-agent: *\nAllow: /',[category]:'<ul class="prdList"><a href="/product/betta/99/">베타</a></ul><div class="xans-product-normalpaging"></div>',[product]:html});
 fs.writeFileSync(path.join(cwd,'transport.cjs'),"const fs=require('fs'),path=require('path'),pages=JSON.parse(fs.readFileSync(path.join(__dirname,'transport.json'))),calls=[];global.fetch=async u=>{calls.push(u);fs.writeFileSync(path.join(__dirname,'calls.json'),JSON.stringify(calls));if(!(u in pages))throw Error('Unexpected URL '+u);return new Response(pages[u],{status:200});};const rename=fs.renameSync.bind(fs);fs.renameSync=(a,b)=>{rename(a,b);if(b==='dist/collector-status.json'){const r=JSON.parse(fs.readFileSync(b));if(r.checkpointOnly)fs.writeFileSync(path.join(__dirname,'captured-partial.json'),JSON.stringify(r));}};");
 const result=spawnSync(process.execPath,['--require',path.join(cwd,'transport.cjs'),'scripts/collect-catalog.cjs','--mode','live','--publish','--quiet'],{cwd,encoding:'utf8',timeout:15000});assert.equal(result.status,0,result.stderr);const catalog=JSON.parse(fs.readFileSync(path.join(cwd,'dist/catalog.json'))),partial=JSON.parse(fs.readFileSync(path.join(cwd,'captured-partial.json'))),final=JSON.parse(fs.readFileSync(path.join(cwd,'.collector/report.json')));assert.ok(catalog.products.some(p=>p.name==='검증 베타'&&p.subtype==='fish'));assert.equal(partial.checkpointOnly,true);assert.equal(partial.finishedAt,null);assert.ok(partial.sources[0].discoveryProgress.categoryTree);assert.equal(final.fullCatalogCoverage,false);assert.ok(final.sources[0].requests<=5);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(cwd,'calls.json'))),[host+'/robots.txt',category,product]);
 }finally{assert.ok(path.resolve(cwd).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(cwd,{recursive:true,force:true});}
});
