'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {selectPlan,limits}=require('../scripts/collect-coverage-batch.cjs');
test('resume refuses a live or unverifiable owner and allows a confirmed terminated owner',()=>{const {assertOwnerExited}=require('../scripts/collect-coverage-batch.cjs');assert.throws(()=>assertOwnerExited({activePid:12},()=>{}),/still running/);assert.throws(()=>assertOwnerExited({activePid:12},()=>{throw Object.assign(Error('Denied'),{code:'EPERM'});}),/Cannot verify/);assert.doesNotThrow(()=>assertOwnerExited({activePid:12},()=>{throw Object.assign(Error('Gone'),{code:'ESRCH'});}));});
function fixture(){const ids=['a','b','c','d','e','f'];return {registry:{sources:ids.map(id=>({id,name:id,enabled:true,maxRequests:20}))},seeds:{sources:ids.map(id=>({id,adapter:'cafe24_category_links'}))},state:{sources:Object.fromEntries(ids.map(id=>[id,{discoveryPending:[{url:'https://'+id+'.invalid/product/fish/1/',type:'live'}]}]))},audit:{sources:ids.map(id=>({id,tree:{allowed:10,unvisited:10},access:{latestAttempt:'2026-10-08T00:00:00Z'}}))}};}
test('bounded batch rotates untouched merchants across exploration and detail draining',()=>{const f=fixture(),session={sourceVisits:{}};const first=selectPlan(f.registry,f.seeds,f.state,f.audit,session);assert.equal(first.length,5);assert.equal(first.filter(p=>p.mode==='drain').length,2);assert.ok(first.every(p=>p.maxRequests===12));for(const p of first)session.sourceVisits[p.id]=1;const next=selectPlan(f.registry,f.seeds,f.state,f.audit,session);assert.equal(next[0].id,'f');});
test('quarantine, future denial backoff and held-only detail queues are not retried',()=>{const f=fixture(),now=Date.parse('2026-10-08T10:00:00Z');f.state.sources.a.requiresManualReview=true;f.state.sources.b.blockedUntil='2026-10-09T10:00:00Z';f.state.sources.c.discoveryPending[0].retryAfter='2026-10-09T10:00:00Z';f.audit.sources.find(s=>s.id==='c').tree.unvisited=0;const plan=selectPlan(f.registry,f.seeds,f.state,f.audit,{sourceVisits:{}},now);assert.ok(plan.every(p=>!['a','b','c'].includes(p.id)));});
test('batch cannot silently exceed three sixty-request rounds or extend collection past thirty-five minutes',()=>{assert.equal(limits([]).totalRequests,180);assert.equal(limits(['--rounds','1']).totalRequests,60);for(const args of [['--rounds','4'],['--minutes','45'],['--rounds','0'],['--minutes','NaN']])assert.throws(()=>limits(args));});
test('pending-first integration drains real queued details without touching unvisited categories',async()=>{const {integrateDiscovery}=require('../scripts/collector/integrate-discovery.cjs'),host='https://example.invalid',product=host+'/product/fish/1/',category=host+'/category/betta/2/',calls=[],html='<h1>베타</h1><p>1,000원</p><script type="application/ld+json">'+JSON.stringify({'@type':'Product',name:'베타',sku:'1',url:product,offers:{'@type':'Offer',price:1000,priceCurrency:'KRW'}})+'</script>';const result=await integrateDiscovery({id:'a',name:'a',sourceDomain:'example.invalid',officialURL:host,enabled:true,maxRequests:2,delayMs:0},{adapter:'cafe24_category_links',maxPages:1,maxProducts:10,maxProductVerifications:3,categories:[{url:category,label:'베타',type:'live',subtype:'fish'}]},{products:[],updatedKeys:[],discoveryPending:[{url:product,type:'live',subtype:'fish',discoveredInCategory:category}],cache:{}},{items:[]},{coverageLive:true,pendingFirst:true,fetch:async u=>{calls.push(u);if(u===host+'/robots.txt')return new Response('User-agent: *\nAllow: /');if(u===product)return new Response(html);throw Error('Unexpected category request');}});assert.deepEqual(calls,[host+'/robots.txt',product]);assert.equal(result.discoveryPending.length,0);assert.equal(result.products.length,1);});
