'use strict';const {test}=require('node:test'),assert=require('node:assert/strict');const {discoverDaily}=require('../scripts/collector/daily-discovery.cjs');const {classifyProduct}=require('../scripts/collector/classification.cjs');const {verifyDiscovered}=require('../scripts/collector/verify-discovered.cjs');
const host='https://example.invalid',url=host+'/category/plants/7/';const source={id:'synthetic',sourceDomain:'example.invalid',name:'fixture',officialURL:host+'/',enabled:true,maxRequests:10,delayMs:0,cacheTtlMs:0,timeoutMs:1000,maxBytes:10000,photosAllowed:false};const seed={adapter:'cafe24_category_links',maxPages:1,maxProducts:2,maxProductVerifications:2,categories:[{url,label:'수초',type:'live',subtype:'aquatic_plant',reviewBasis:'Synthetic verified category'}]};
function page(ids,next){return '<div class="prdCount">4개</div><ul class="prdList">'+ids.map(i=>`<a href="/product/p${i}/${i}/">p${i}</a>`).join('')+'</ul><div class="xans-product-normalpaging">'+(next?`<a href="?page=${next}">next</a>`:'')+'</div>';}
function transport(pages){const calls=[];return {calls,fetch:async u=>{calls.push(u);return new Response(u.endsWith('/robots.txt')?'User-agent: *\nAllow: /':pages[u]||'not found',{status:u.endsWith('/robots.txt')||pages[u]?200:404});},sleep:async()=>{}};}
test('saved actual next-page cursor resumes, probing first page does not erase pending tail',async()=>{
 const first=await discoverDaily(source,seed,{},transport({[url]:page([1,2],2)}));assert.equal(first.products.length,2);assert.equal(Object.values(first.cursor.categories)[0].nextUrl,url+'?page=2');
 const second=await discoverDaily(source,{...seed,maxPages:2},first,transport({[url]:page([1,2],2),[url+'?page=2']:page([3,4])}));assert.equal(second.categories[0].headProbe,true);assert.deepEqual(second.products.map(p=>p.url),[host+'/product/p3/3/',host+'/product/p4/4/']);assert.equal(second.coverage.coverageComplete,false);assert.equal(second.coverage.deletionAllowed,false);
});
test('product-budget interruption resumes the same observed page without losing remaining ids',async()=>{
 const a=await discoverDaily(source,{...seed,maxProducts:1},{},transport({[url]:page([1,2],2)}));assert.equal(Object.values(a.cursor.categories)[0].nextUrl,url);const b=await discoverDaily(source,{...seed,maxProducts:1},a,transport({[url]:page([1,2],2)}));assert.equal(b.products[0].url,host+'/product/p2/2/');assert.equal(Object.values(b.cursor.categories)[0].nextUrl,url+'?page=2');
});
test('round-robin category index prevents one large category monopolizing every daily budget',async()=>{const second=host+'/category/fish/8/',two={...seed,categories:[...seed.categories,{...seed.categories[0],url:second}]};const a=await discoverDaily(source,two,{},transport({[url]:page([1,2],2)}));assert.equal(a.cursor.nextCategoryIndex,1);const b=await discoverDaily(source,two,a,transport({[second]:page([5,6],2)}));assert.equal(b.categories[0].url,second);});
test('unsupported adapters and denied sources are explicit and make no discovery requests',async()=>{const t={fetch:()=>{throw Error('must not fetch')}};assert.equal((await discoverDaily(source,{...seed,adapter:'not_implemented'},{},t)).status,'adapter_not_implemented');assert.equal((await discoverDaily({...source,enabled:false},seed,{},t)).status,'disabled');});
test('live-food shrimp, supplies, artificial plants and terrestrial animals cannot become ornamental livestock',()=>{
 const mixed={url:host+'/product/x/1/',type:null,subtype:null,mixedCategories:true};const bread='<div class="ec-base-path"><a href="/category/food/9/">사료/먹이</a><a href="/category/livefeed/10/">생먹이</a></div>';assert.equal(classifyProduct(bread,{title:'생이새우 (생먹이)'},mixed,seed).type,'gear');
 for(const title of ['인조 수초','수초용품 핀셋','동결건조 새우','수초 비료'])assert.equal(classifyProduct('',{title},{...mixed,type:'live',subtype:'aquatic_plant',mixedCategories:false},seed).status,'needs_review');assert.equal(classifyProduct('',{title:'육지달팽이'},mixed,seed).status,'excluded_scope');assert.equal(classifyProduct('',{title:'새우'},mixed,seed).status,'needs_review');
});
test('verified retailer breadcrumb and detail identity classify a real plant but never fabricate registration or sales',async()=>{
 const candidate={url:host+'/product/plant/1/',type:'live',subtype:'aquatic_plant',mixedCategories:false,discoveredInCategory:url};const html='<div class="ec-base-path"><a href="/category/plants/7/">수초</a></div><h1>실제 수초</h1><p>1,000원</p><script type="application/ld+json">'+JSON.stringify({'@type':'Product',name:'실제 수초',sku:'p1',url:candidate.url,offers:{'@type':'Offer',price:1000,priceCurrency:'KRW'}})+'</script>';const out=await verifyDiscovered(source,seed,[candidate],{},transport({[candidate.url]:html}));assert.equal(out.status,'success');assert.equal(out.products.length,1);assert.equal(out.products[0].type,'live');assert.equal(out.products[0].subtype,'aquatic_plant');assert.equal(out.products[0].registered_at,null);assert.equal(out.products[0].shipping_amount,null);assert.ok(out.products[0].classification_basis.includes('breadcrumb'));
});
test('139 representative links belong to 32 enabled original sources and never prove full source completeness',()=>{const registry=require('../sources/registry.json'),map=require('../sources/discovery-seeds.json');assert.equal(map.sources.length,32);assert.equal(map.sources.reduce((n,s)=>n+s.categories.length,0),139);assert.equal(map.sources.filter(s=>s.adapter==='cafe24_category_links').length,26);for(const s of map.sources){assert.equal(registry.sources.find(r=>r.id===s.id).enabled,true);assert.equal(s.allSourceCategoriesReviewed,false);}});
test('price refresh includes discovered verified URLs and rotates with a reserved daily discovery budget',()=>{const {refreshScope}=require('../scripts/collector/refresh-scope.cjs');const original={...source,products:[]},previous={products:Array.from({length:22},(_,i)=>({id:'p'+i,source_id:source.id,product_url:host+'/product/item/'+(i+1)+'/',type:'live',subtype:'fish'}))};const a=refreshScope(original,previous,'live',false);assert.equal(a.products.length,15);const b=refreshScope(original,{...previous,priceRefreshCursor:a.cursor},'live',false);assert.equal(b.products[0].existingId,'p15');assert.equal(refreshScope(original,previous,'all',true).products.length,10);assert.equal(a.summary.fullRetailerCatalogCoverage,false);});
test('integrated add flow shares the source request budget and retains unverified pending URLs',async()=>{const {integrateDiscovery}=require('../scripts/collector/integrate-discovery.cjs');const candidatesPage=page([1,2]);const detail='<h1>수초 하나</h1><p>1,000원</p><script type="application/ld+json">'+JSON.stringify({'@type':'Product',name:'수초 하나',sku:'p1',url:host+'/product/p1/1/',offers:{'@type':'Offer',price:1000,priceCurrency:'KRW'}})+'</script>';const t=transport({[url]:candidatesPage,[host+'/product/p1/1/']:detail}),out=await integrateDiscovery({...source,maxRequests:4,cacheTtlMs:10800000},seed,{status:'success',requests:1,products:[],updatedKeys:[]},{items:[]},t);assert.ok(out.requests<=4);assert.equal(out.products.length,1);assert.equal(out.products[0].subtype,'aquatic_plant');assert.equal(out.discoveryPending.length,1);assert.equal(out.discoverySummary.deletionEnabled,false);assert.equal(out.discoverySummary.coverageComplete,false);});
test('raw cache expiry and size bounds do not alter lastgood products',()=>{const {pruneCache}=require('../scripts/collector/cache-policy.cjs'),now=Date.now(),current=new Date(now).toISOString(),old=new Date(now-2*86400000).toISOString();const cache={old:{text:'old',fetchedAt:old},...Object.fromEntries(Array.from({length:70},(_,i)=>['https://example.invalid/'+i,{text:'x',fetchedAt:current}]))};const pruned=pruneCache(cache,now);assert.equal(Object.keys(pruned).length,60);assert.equal(pruned.old,undefined);assert.deepEqual(pruneCache({huge:{text:'x'.repeat(12000001),fetchedAt:current}},now),{});});
