'use strict';
const {categoryKey}=require('./discovery.cjs');
const VOID=new Set(['area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr']);
const text=s=>String(s||'').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/\s+/g,' ').trim();
const {FISH:fish,identities,UNSUPPORTED}=require('./product-evidence.cjs');
const {categoryEligible,discoveryScope,laneField}=require('./discovery-scope.cjs');
const supplies=/사료|먹이|용품|장식|모형|인조|조명|여과|어항|수조|침대|과립|플레이크|치어용|램프|소켓|약품|치료제|제거제|달팽이제거|소일|바닥재|비료|씨앗|알테미아|브라인|냉동|건조|히터|온도계|냉각|쿨러|기포|에어|산소|수중펌프|수질|박테리아|염소|CO2|이산화탄소|확산|밸브|호스|튜브|스키머|청소용품|청소도구|청소기|뜰채|사이펀|싸이펀|스크래퍼|핀셋|가위|집게|유목|석재|받침|축양|타이머|콘센트|멀티탭|스포이드|분배기|부화통|격리통|산란통|뚜껑|매트|브라켓/i;
function scope(label,ancestors=[]){const lineage=[...ancestors,label].join(' > '),own=identities(label);
 const mixedLabel=s=>/[/&|]/.test(s)&&s.split(/[/&|]/).some(part=>identities(part).length>0&&!supplies.test(part))&&(supplies.test(s)||/양서|거북/.test(s));
 if(/수조크기별|어항크기별|소일포트수초|활착.*유목|유목.*활착/.test(label)||mixedLabel(label))return {scope:'mixed',type:null,subtype:null,mixedCategories:true,reason:'Mixed or ambiguous browsing menu; final classification requires primary product content'};
 const restrictiveAncestors=ancestors.filter(a=>!mixedLabel(a)&&!(own.length===1&&UNSUPPORTED.test(a)&&!/사료|먹이|용품|장식/.test(a)));
 if(UNSUPPORTED.test(label)||restrictiveAncestors.some(a=>UNSUPPORTED.test(a)))return {scope:'excluded',reason:'Unsupported terrestrial/reptile/amphibian or preorder menu'};
 if(supplies.test(label)||restrictiveAncestors.some(a=>supplies.test(a)))return {scope:'gear',type:'gear',subtype:null,mixedCategories:false,reason:'Observed aquarium supply/feed menu ancestry; primary product detail must be verified'};
 const matches=[];if(fish.test(lineage))matches.push('fish');if(/새우|shrimp|CRS|CBS/i.test(lineage))matches.push('shrimp');if(/수초|음성수초|양성수초|활착수초/.test(lineage))matches.push('aquatic_plant');if(/스네일|달팽이|우렁이|snail/i.test(lineage))matches.push('snail');
 // Specific leaf overrides a broad aquatic parent, but unrelated sibling labels never enter ancestry.
 const leaf=[];if(fish.test(label))leaf.push('fish');if(/새우|shrimp|CRS|CBS/i.test(label))leaf.push('shrimp');if(/수초/.test(label))leaf.push('aquatic_plant');if(/스네일|달팽이|우렁이|snail/i.test(label))leaf.push('snail');
 if(leaf.length===1)return {scope:'live',type:'live',subtype:leaf[0],mixedCategories:false};
 if(!leaf.length&&matches.length===1)return {scope:'live',type:'live',subtype:matches[0],mixedCategories:false};
 if(matches.length||/^(전체\s*)?(생물|생물분양|관상생물)$/.test(label.replace(/\s*\([\d,]*\)/g,'')))return {scope:'mixed',type:null,subtype:null,mixedCategories:true};
 if(/가재|갑각류/.test(label))return {scope:'excluded',reason:'Unsupported crustacean category without an explicit ornamental-shrimp leaf'};
 return {scope:'review',reason:'No explicit aquatic-category lineage'};
}
function categoryLinks(html,pageUrl,source,adapter,pageContext=[]){const routes=adapter==='cafe24_category_links'?require('./discovery.cjs'):require('./legacy-discovery.cjs'),stack=[],records=[];
 const input=String(html).replace(/<!--[\s\S]*?-->|<(script|style)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,'');
 function close(frame){if(frame.tag!=='a'||!frame.href)return;const label=text(frame.text);if(!label||label.length>100)return;const url=routes.categoryUrl(frame.href,pageUrl,source.officialURL);if(!url)return;const u=new URL(url);u.searchParams.delete('page');u.searchParams.delete('sort');u.searchParams.delete('sort_method');const ancestors=stack.filter(f=>f.tag==='li'&&f.primaryLabel).map(f=>f.primaryLabel);const own=stack.findLast(f=>f.tag==='li');if(own?.primaryLabel===label)ancestors.pop();if(adapter==='cafe24_category_links'&&stack.some(f=>f.categoryMenu))ancestors.unshift(...pageContext);const classification=scope(label,ancestors);records.push({key:categoryKey(u.href),url:u.href,label,ancestorLabels:ancestors,evidencePage:pageUrl,...classification});if(own&&!own.primaryLabel)own.primaryLabel=label;}
 for(const token of input.match(/<[^>]+>|[^<]+/g)||[]){if(!token.startsWith('<')){for(const f of stack)if(f.tag==='a')f.text+=token;continue;}const closing=token.match(/^<\/([\w-]+)/);if(closing){const at=stack.findLastIndex(f=>f.tag===closing[1].toLowerCase());if(at>=0){const popped=stack.splice(at);for(const f of popped.reverse())close(f);}continue;}const opening=token.match(/^<([\w-]+)/);if(!opening)continue;const tag=opening[1].toLowerCase(),href=token.match(/\bhref\s*=\s*(?:"([^"]*)"|'([^']*)')/i);const menuClasses=token.match(/\bclass\s*=\s*(?:"([^"]*)"|'([^']*)')/i);const f={tag,categoryMenu:menuClasses?(menuClasses[1]??menuClasses[2]).split(/\s+/).includes('menuCategory'):false,href:href?text(href[1]??href[2]):null,text:''};if(!VOID.has(tag)&&!token.endsWith('/>'))stack.push(f);}
 return records;
}
function mergeTree(source,seed,state,options={}){const requestedScope=discoveryScope(options),records=new Map((state.categoryTree?.nodes||[]).map(n=>[n.key,n.reviewedSeed?{...n,scope:n.type==='gear'&&!n.excluded?'gear':n.scope}:{...n,...scope(n.label,n.ancestorLabels||[]),excluded:scope(n.label,n.ancestorLabels||[]).scope==='excluded',scopeVersion:3}]));for(const c of seed.categories||[]){const key=categoryKey(c.url);if(!key)continue;if(!records.has(key))records.set(key,{key,...c,scope:c.excluded?'excluded':c.type==='live'?'live':c.type==='gear'?'gear':c.mixedCategories?'mixed':'review',evidencePage:c.evidencePage||c.url,evidenceObservedAt:c.evidenceObservedAt||null,reviewedSeed:true});}
 for(const [url,cache]of Object.entries(state.cache||{})){if(!cache?.text||url.endsWith('/robots.txt'))continue;let same=false;try{same=new URL(url).hostname.replace(/^www\./,'')===new URL(source.officialURL).hostname.replace(/^www\./,'');}catch{}if(!same)continue;const parent=records.get(categoryKey(url)),pageContext=parent&&['live','gear','mixed','excluded'].includes(parent.scope)?[...(parent.ancestorLabels||[]),parent.label].filter(Boolean):[];for(const n of categoryLinks(cache.text,url,source,seed.adapter,pageContext)){const old=records.get(n.key);if(old?.reviewedSeed)continue;
 // Keep provenance and revisit decisions; never let an older flat menu erase newer evidence.
 if(old?.evidenceObservedAt&&Date.parse(old.evidenceObservedAt)>Date.parse(cache.fetchedAt))continue;
 if(old&&['live','gear','mixed'].includes(old.scope)&&n.scope==='review')continue;
 const priorScope=old?.scope;records.set(n.key,{...old,...n,priorScope,scopeVersion:3,evidenceObservedAt:cache.fetchedAt,firstObservedAt:old?.firstObservedAt||cache.fetchedAt,reviewBasis:'Observed same-retailer public navigation; discovery hint only, primary detail classification required',requiresProductClassification:true,excluded:n.scope==='excluded'});}}
 const nodes=[...records.values()],known=new Set(seed.categories.map(c=>categoryKey(c.url))),extra=nodes.filter(n=>['live','gear','mixed'].includes(n.scope)&&!known.has(n.key));const all=[...seed.categories.filter(c=>{const n=records.get(categoryKey(c.url));return n?.reviewedSeed||n?.scope!=='excluded';}),...extra];
 return {tree:{schemaVersion:1,nodes,discoveredCategoryCount:nodes.length,allowedCategoryCount:all.filter(c=>categoryEligible(c,requestedScope)).length,excludedCategoryCount:nodes.filter(n=>n.scope==='excluded').length,reviewCategoryCount:nodes.filter(n=>n.scope==='review').length,fullMenuCoverage:'unknown',scope:'aquarium_live_and_gear',scopeVersion:3},seed:{...seed,categories:all,exploreWithBacklog:true,maxPagesPerCategory:seed.maxPagesPerCategory||1}};
}
function treeProgress(state,requestedScope='live'){const tree=state.categoryTree;if(!tree)return null;const cursor=state[laneField(requestedScope)]?.cursor?.categories||{},allowed=tree.nodes.filter(n=>categoryEligible(n,requestedScope));const terminal=allowed.filter(n=>cursor[n.key]?.lastCycle?.terminalPageReached===true&&cursor[n.key]?.nextUrl===null);const pages=[...new Set(Object.values(cursor).flatMap(c=>c.visitedPageUrls||[]))];const pending=allowed.filter(n=>!cursor[n.key]||cursor[n.key].nextUrl!==null);
 return {discoveryScope:requestedScope,discoveredCategoryCount:tree.nodes.length,allowedCategoryCount:allowed.length,excludedCategoryCount:tree.excludedCategoryCount,reviewCategoryCount:tree.reviewCategoryCount,pagesVisited:pages.length,pendingCategoryCount:pending.length,pendingPageUrls:pending.map(n=>({categoryUrl:n.url,nextPageUrl:cursor[n.key]?.nextUrl||n.url})),terminalCategoryCount:terminal.length,verifiedProductCount:state.products?.length||0,pendingProductCount:state.discoveryPending?.length||0,reviewProductCount:state.discoveryReviewQueue?.length||0,menuCoverage:'unknown',terminalCoverage:allowed.length&&terminal.length===allowed.length?'observed_categories_terminal':'incomplete',fullRetailerCoverage:false};
}
module.exports={scope,categoryLinks,mergeTree,treeProgress,supplies};
