'use strict';
const {visibleText,priceIsVisible}=require('./product-jsonld.cjs');
const {scanHtml}=require('./discovery.cjs');
function attrs(tag){const out={};for(const m of tag.matchAll(/([\w:-]+)\s*=\s*(["'])(.*?)\2/g))out[m[1].toLowerCase()]=m[3];return out;}
function safe(href,base){try{const u=new URL(href.replaceAll('&amp;','&'),base);if(u.protocol!=='https:'||u.username||u.password||u.hostname.replace(/^www\./,'')!=='wpet.co.kr'||u.pathname!=='/')return null;u.hash='';return u;}catch{return null;}}
function categoryUrl(href,base){const u=safe(href,base);return u&&u.searchParams.get('act')==='shop.goods_list'&&/^GD\d+$/.test(u.searchParams.get('GC')||'')&&[...u.searchParams.keys()].every(k=>['act','GC','page'].includes(k))&&(!u.searchParams.has('page')||/^[1-9]\d*$/.test(u.searchParams.get('page')))?u.href:null;}
function parseCategoryPage(html,pageUrl){const scan=scanHtml(html,{listClasses:['ui_shop_good_list'],pagerClasses:['paging']}),products=new Map(),pages=new Map(),current=Number(new URL(pageUrl).searchParams.get('page')||1),gc=new URL(pageUrl).searchParams.get('GC');for(const a of scan.links){const u=safe(a.href,pageUrl);if(!u)continue;if(a.inList&&u.searchParams.get('act')==='shop.goods_view'&&/^[1-9]\d*$/.test(u.searchParams.get('CM')||'')&&[...u.searchParams.keys()].every(k=>['act','GC','CM'].includes(k)))products.set(u.searchParams.get('CM'),u.href);if(a.inPager){const url=categoryUrl(u.href,pageUrl);if(url&&u.searchParams.get('GC')===gc){const page=Number(u.searchParams.get('page')||1);if(page>current)pages.set(page,url);}}}const issues=[];if(!scan.listFound)issues.push('product_list_not_found');const nextPage=pages.get(current+1)||null;if(pages.size&&!nextPage)issues.push('pagination_gap');return {products:[...products.values()],expectedTotal:null,nextPage,terminal:scan.listFound&&scan.paginationFound&&!pages.size&&issues.length===0,issues};}
function parseWpetPage(html,context){
 const fail=issue=>({status:'parse_failed',items:[],issues:[issue]}),url=safe(context.url,context.url);if(!url||url.searchParams.get('act')!=='shop.goods_view'||!/^[1-9]\d*$/.test(url.searchParams.get('CM')||''))return fail('wpet_detail_route_unverified');
 const metas=[...html.matchAll(/<meta\b[^>]*>/gi)].map(m=>attrs(m[0])),canonicalRaw=metas.find(m=>m.property==='og:url')?.content,canonical=canonicalRaw?safe(canonicalRaw,context.url):null;if(!canonical||canonical.searchParams.get('act')!=='shop.goods_view'||canonical.searchParams.get('CM')!==url.searchParams.get('CM'))return fail('wpet_canonical_identity_mismatch');
 const inputs=[...html.matchAll(/<input\b[^>]*>/gi)].map(m=>attrs(m[0])),field=name=>{const a=inputs.filter(i=>i.name===name);return a.length===1?a[0].value:null;},seq=field('good_seq'),raw=field('good_price');if(!/^[1-9]\d*$/.test(seq||''))return fail('wpet_goods_identity_unverified');
 const title=visibleText(html.match(/<td\b[^>]*class=["'][^"']*\bproduct_big_title\b[^"']*["'][^>]*>([\s\S]*?)<\/td>/i)?.[1]||''),metaTitle=metas.find(m=>m.property==='og:title')?.content;if(!title||visibleText(metaTitle||'')!==title)return fail('wpet_title_not_corroborated');
 let data;try{data=JSON.parse(html.match(/PRODUCT_PRICE_ARRAY\s*:\s*(\{[\s\S]*?\}),\s*IS_SIMPLE_PRICE\s*:/)?.[1]);}catch{return fail('wpet_public_offer_unverified');}
 const offers=data.price_list,amount=Number(raw),primary=html.match(/<th\b[^>]*>\s*판매가\s*<\/th>\s*<th\b[^>]*>([\s\S]*?)<\/th>/i)?.[1];
 if(!/^\d+$/.test(raw||'')||!Number.isSafeInteger(amount)||!primary||!priceIsVisible(visibleText(primary),amount)||String(data.price_sale)!==raw)return fail('wpet_primary_price_not_corroborated');
 if(!Array.isArray(offers)||offers.length!==1||offers[0].good_opt_val_seq!==seq||offers[0].good_price!==raw||visibleText(offers[0].good_name||'')!==title||visibleText(data.name||'')!==title||data.xtitle||data.ytitle||!(/IS_SIMPLE_PRICE\s*:\s*'1'/.test(html)))return fail('wpet_single_offer_identity_mismatch');
 for(const key of ['multiple_options_required','input_options_required','addition_options_required'])if(data[key]&&data[key].length)return fail('wpet_required_option_unverified');
 if(!['live','gear'].includes(context.type))return fail('verified_category_required');
 const imageTags=[...html.matchAll(/<img\b[^>]*>/gi)].map(m=>attrs(m[0])),image=imageTags.find(i=>i.id==='img_good_view')?.src;let photo=null;try{const u=new URL(image,context.url);if(context.photosAllowed===true&&u.protocol==='https:'&&u.hostname.replace(/^www\./,'')==='wpet.co.kr'&&u.pathname.startsWith('/data/goods/')&&u.pathname.split('/').includes(seq))photo={verified_https_url:u.href,permission_basis:'explicit_user_instruction',source_page_url:context.url,downloaded_or_rehosted:false};}catch{}
 const key=context.sourceId+':'+seq+':default';return {status:'success',issues:[],items:[{id:context.existingId||key,collector_key:key,source_id:context.sourceId,retailer_product_id:seq,variant_id:null,retailer:context.name,seller_domain:'wpet.co.kr',source_kind:'direct_retailer_product_page',verification_method:'Public single-offer goods identity and hidden base price matched canonical detail, visible primary product name and KRW sales row',type:context.type,subtype:context.subtype??null,title,product_url:context.url,observed_at_utc:context.observedAt,registered_at:null,price_amount:amount,currency:'KRW',shipping_amount:null,available:null,availability_basis:'Inventory and checkout availability not independently verified',stock_quantity:null,quantity_per_pack:null,variant_title:null,photo}]};
}
module.exports={categoryUrl,parseCategoryPage,parseWpetPage};
